### ISSUE TITLE
diff_match_patch is not defined

### ISSUE THREAD

**Issue by Gokul-15** [amweiss/angular-diff-match-patch#104]
how to resolve this issue ??

**Comment by amweiss** [comment]
Did you use npm, Bower, or webpack? Can you post some code or screenshots?

**Comment by Gokul-15** [comment]
used NPM

**Comment by amweiss** [comment]
You most likely need to just include the diff_match_patch dependency somehow. If you use npm or the like it would look like this:

```html
<script src="node_modules/diff-match-patch/index.js"></script>
<script src="node_modules/angular-diff-match-patch/angular-diff-match-patch.js"></script>
```
