### ISSUE TITLE
source missing license header

### ISSUE THREAD

**Issue by KelseyBlodgett** [amweiss/angular-diff-match-patch#14]
I noticed that the JavaScript file doesn't have a license header. This seems to be a common practice amongst JavaScript libraries.
Would it be possible to add the information to the file so users can easily adhere to the project's license?
Something like:
Licensed under the MIT License
Thanks.

**Comment by amweiss** [comment]
Sure, this is easy enough.  I'll try to get it added today.

**Comment by amweiss** [comment]
Resolved in 74d6969f6079bd37b1dcf6ce400c08b840246ff5 and released in 0.1.12
