### ISSUE TITLE
Input produces errors

### ISSUE THREAD

**Issue by jarischaefer** [amweiss/angular-diff-match-patch#146]
> See the included demo for reference or view a sample on Codepen.

I used the example on your [Codepen](https://codepen.io/amweiss/pen/grXNPm).
When I enter `{{ range test }}`, an error appears in the console.

> Error: "[$parse:syntax] Syntax Error: Token 'test' is an unexpected token at column 7 of the expression [range test] starting at [test].
https://errors.angularjs.org/1.7.2/$parse/syntax?p0=test&p1=is%20an%20unexpected%20token&p2=7&p3=range%20test&p4=test"

Looks like an unintended evaluation of the expression.

**Comment by amweiss** [comment]
You can specify to skip the compiling if you want in the options:
`skipAngularCompilingOnDiff: true` 

Then the error will go away.
