### ISSUE TITLE
IE11 error starting with v0.7.52

### ISSUE THREAD

**Issue by jonathanray** [amweiss/angular-diff-match-patch#148]
A few days ago, I upgraded from v0.7.28 to v0.7.52 and discovered the page no longer renders in IE11.

This is console error in IE11
![image](https://user-images.githubusercontent.com/6164433/80121734-4df5fa80-8552-11ea-915c-7bbda8c2bd00.png)

It links to this line which uses a for-of loop, which is not supported in IE11
https://github.com/amweiss/angular-diff-match-patch/blob/7066e0fa3125eca7e63c28de7b626830238a0416/angular-diff-match-patch.js#L209

**Comment by amweiss** [comment]
This should be fixed in v0.7.75 going to npm now.

**Comment by jonathanray** [comment]
That line contained two language features that IE11 doesn't support: a `for-of` loop and `const`. I just tested and that line still breaks IE11 due to the for-of loop.

![image](https://user-images.githubusercontent.com/6164433/80224524-6bd56500-860f-11ea-81c4-c6e5ae719d4c.png)

**Comment by amweiss** [comment]
Give v0.7.76 a try

**Comment by jonathanray** [comment]
I confirmed v0.7.76 works as expected in IE11.

Thank you so much for the quick turnaround, and more importantly taking your time to maintain open source software.

**Comment by amweiss** [comment]
No problem, glad it's working now. Apparently along the way the linter increased their minimum supported versions so it left IE 11 out. Hopefully it stays fixed now 😅
