### ISSUE TITLE
ReferenceError: Can't find variable: module

### ISSUE THREAD

**Issue by benji1298** [amweiss/angular-diff-match-patch#23]
Not sure if this is an error in the wrapper or in the actual google-diff-match-patch library. Either way, it breaks my Karma tests.

I was able to fix it by removing:
`module.exports = diff_match_patch;
module.exports['diff_match_patch'] = diff_match_patch;
module.exports['DIFF_DELETE'] = DIFF_DELETE;
module.exports['DIFF_INSERT'] = DIFF_INSERT;
module.exports['DIFF_EQUAL'] = DIFF_EQUAL;`
From the end of /node_modules/diff-match-patch/index.js, but I'm guessing that is not a proper solution.

Any guidance? If this issue is better suited for the google-diff-match-patch repo, let me know and I'll make one over there.

**Comment by amweiss** [comment]
It's part of the google-diff-match-patch repo, but you should only be including that file if you are running from node. If you are just running from a browser, don't pull in that file. You can see the front-end only example at http://adamweiss.me/angular-diff-match-patch/
