### ISSUE TITLE
LineDiff + SemanticDiff combined?

### ISSUE THREAD

**Issue by pingec** [amweiss/angular-diff-match-patch#26]
How hard would it be to produce a combined diff like in this example? http://i.stack.imgur.com/o3L0f.png

**Comment by amweiss** [comment]
Do you mean just the lines and diff's themselves or the patch/unidiff format with headers about where the changes are? (See #25 for the latter).

If it's just the lines and diffs being a different highlighting, I'll have to see if that's native to the library or not.

**Comment by pingec** [comment]
Sorry for not being specific enough. I meant just the different shades of highlight for lines and diffs...

**Comment by amweiss** [comment]
Ok, that should be possible I'll take a look.

**Comment by amweiss** [comment]
I've been looking a this, and the way the library works by default makes it nearly impossible since it does a diff across newlines. I can try to split the lines and then do diffs but it will be quite inefficient.

**Comment by pingec** [comment]
Thanks for looking into this. Since I have smaller files/diffs I could definitely live with an inefficient solution.

**Comment by amweiss** [comment]
It looks like most of the tools that do this highlighting only work when it's a single line with changes on both sides like this in github.
![image](https://cloud.githubusercontent.com/assets/30146/17538711/f86289fa-5e75-11e6-8025-237d8c20bc7e.png)

The problem I'm seeing is that the diffs themselves span across line breaks which makes correctly closing tags correctly escape me at the time being. I'll start with the single line versions to see if I can make it match this display.

**Comment by amweiss** [comment]
Take a look at https://github.com/amweiss/angular-diff-match-patch/tree/feature/diff-lines
specifically https://github.com/amweiss/angular-diff-match-patch/commit/42f2a98ea4f8c43cebce04eeac29d07a1268cc51 you can style as desired, but it should do the diff within the one line diffs.

![image](https://cloud.githubusercontent.com/assets/30146/17539455/71429bde-5e7c-11e6-985e-7150b5a1b736.png)

**Comment by amweiss** [comment]
Added in v0.3.0 as optional.

**Comment by pingec** [comment]
Great work, thanks!
