### ISSUE TITLE
Upgrade to angular2

### ISSUE THREAD

**Issue by ufoscout** [amweiss/angular-diff-match-patch#34]
Now that angular2 has been finally released, is there any plan to upgrade this library to angular 2?

**Comment by amweiss** [comment]
That's a great question. I honestly haven't been keeping up with Angular2. I can start to look into it, but it will most likely take a while. As always, pull requests or even a fork at this point are welcome.

**Comment by amweiss** [comment]
See https://github.com/elliotforbes/ng-diff-match-patch
