### ISSUE TITLE
Newline character is considered as a change

### ISSUE THREAD

**Issue by VasuBhaskar** [amweiss/angular-diff-match-patch#37]
When two line are compared as below, eventhough there is only one new line added, tiger is shown as a changed line, as it contains a new line character after tiger now. Can this be fixed

tiger
lion

tiger

**Comment by amweiss** [comment]
It is technically a new character as the line does not have a return at the end.

if you try:
```
tiger
lion
```

```
tiger
other
lion
```

You will see what I think you are suspecting since the line with tiger already has a return at the end.

**Comment by VasuBhaskar** [comment]
<img width="1400" alt="screen shot 2017-01-30 at 11 42 14 am" src="https://cloud.githubusercontent.com/assets/20825655/22434325/3451a218-e6e1-11e6-9486-07d8b1374992.png">

**Comment by VasuBhaskar** [comment]
In the above example in the screen shot given, Hi is still the same in the right and left sides . But the line is shown as deleted and added in linedeiff. Could you please help me with this.

Is there a way i can somehow handle this in the tool to not to show "Hi" as changed line

**Comment by amweiss** [comment]
`ignoreTrailingNewLines` added to options for lineDiff

**Comment by VasuBhaskar** [comment]
Thanks a lot!!
