### ISSUE TITLE
Publish new versions of angular-diff-match-patch to NPM

### ISSUE THREAD

**Issue by jylar** [amweiss/angular-diff-match-patch#39]
[0.1.14 is the latest release available through NPM](https://www.npmjs.com/package/angular-diff-match-patch).
[The latest release 0.6.1](https://github.com/amweiss/angular-diff-match-patch/releases/tag/v0.6.1) and anything else since March 2016 isn't available on NPM.

Please publish the newer versions of your package to NPM so our project can avoid using the deprecated package manager Bower.

**Comment by amweiss** [comment]
You can just use the GitHub syntax `mygithubuser/myproject` in your package file to always have the latest.

**Comment by amweiss** [comment]
More specifically, if you want a version:
`"angular-diff-match-patch": "amweiss/angular-diff-match-patch.git#~0.6`

**Comment by jylar** [comment]
The GitHub syntax (mygithubuser/myproject) can't always be used, for example when a local NPM registry is used to proxy and cache NPM modules.

Visiting/querying NPM also gives the false impression that there is nothing newer than 0.1.14 released.

IMHO, publishing all versions to NPM would solve a lot of avoidable problems.

**Comment by amweiss** [comment]
I don't own the entry in npmjs.com someone else posted my package: https://www.npmjs.com/package/angular-diff-match-patch. I can try to get ownership of it, but there's no guarantee it will work.

**Comment by amweiss** [comment]
https://www.npmjs.com/package/angular-diff-match-patch is now mine and I pushed the latest version after fighting with circleci quite a bit, no functionality differences between 0.6.1 and 0.6.10, just changes to ci. I can look into publishing the older versions as well now, but I'm not sure how npm likes old versions getting published.

**Comment by jylar** [comment]
Thanks! :thumbsup:
