### ISSUE TITLE
Failed to install this repo

### ISSUE THREAD

**Issue by PurpleSun** [amweiss/angular-diff-match-patch#4]
Execute `bower install angular-diff-match-patch --save` and got follow message:
```
bower angular-diff-match-patch#*           cached https://github.com/amweiss/angular-diff-match-patch.git#0.1.6
bower angular-diff-match-patch#*         validate 0.1.6 against https://github.com/amweiss/angular-diff-match-patch.git#*
bower google-diff-match-patch#*        not-cached svn+http://google-diff-match-patch.googlecode.com/svn/#*
bower google-diff-match-patch#*           resolve svn+http://google-diff-match-patch.googlecode.com/svn/#*
bower google-diff-match-patch#*           ECMDERR Failed to execute "svn list http://google-diff-match-patch.googlecode.com/svn/tags --verbose", exit code of #1

Additional error details:
svn: E175002: Unable to connect to a repository at URL 'http://google-diff-match-patch.googlecode.com/svn/tags'
svn: E175002: OPTIONS of 'http://google-diff-match-patch.googlecode.com/svn/tags': could not connect to server (http://google-diff-match-patch.googlecode.com)
```
Any ideas on how to install it properly? Thank you.

**Comment by amweiss** [comment]
It just worked for me:

    PS C:\Users\aweiss\Documents\repos\testing> bower install angular-diff-match-patch --save
    bower angular-diff-match-patch#*       not-cached git://github.com/amweiss/angular-diff-match-patch.git#*
    bower angular-diff-match-patch#*          resolve git://github.com/amweiss/angular-diff-match-patch.git#*
    bower angular-diff-match-patch#*         download https://github.com/amweiss/angular-diff-match-patch/archive/v0.1.6.tar.gz
    bower angular-diff-match-patch#*          extract archive.tar.gz
    bower angular-diff-match-patch#*         resolved git://github.com/amweiss/angular-diff-match-patch.git#0.1.6
    bower google-diff-match-patch#*        not-cached svn+http://google-diff-match-patch.googlecode.com/svn/#*
    bower google-diff-match-patch#*           resolve svn+http://google-diff-match-patch.googlecode.com/svn/#*
    bower angular-mocks#>= 1.2.0 < 1.4.x       cached git://github.com/angular/bower-angular-mocks.git#1.3.7
    bower angular-mocks#>= 1.2.0 < 1.4.x     validate 1.3.7 against git://github.com/angular/bower-angular-mocks.git#>= 1.2.0 < 1.4.x
    bower angular#>= 1.2.0 < 1.4.x             cached git://github.com/angular/bower-angular.git#1.3.7
    bower angular#>= 1.2.0 < 1.4.x           validate 1.3.7 against git://github.com/angular/bower-angular.git#>= 1.2.0 < 1.4.x
    bower angular-mocks#>= 1.2.0 < 1.4.x          new version for git://github.com/angular/bower-angular-mocks.git#>= 1.2.0 < 1.4.x
    bower angular-mocks#>= 1.2.0 < 1.4.x      resolve git://github.com/angular/bower-angular-mocks.git#>= 1.2.0 < 1.4.x
    bower angular-mocks#>= 1.2.0 < 1.4.x     download https://github.com/angular/bower-angular-mocks/archive/v1.3.13.tar.gz
    bower angular#>= 1.2.0 < 1.4.x                new version for git://github.com/angular/bower-angular.git#>= 1.2.0 < 1.4.x
    bower angular#>= 1.2.0 < 1.4.x            resolve git://github.com/angular/bower-angular.git#>= 1.2.0 < 1.4.x
    bower angular#>= 1.2.0 < 1.4.x           download https://github.com/angular/bower-angular/archive/v1.3.13.tar.gz
    bower angular-mocks#>= 1.2.0 < 1.4.x      extract archive.tar.gz
    bower angular-mocks#>= 1.2.0 < 1.4.x     resolved git://github.com/angular/bower-angular-mocks.git#1.3.13
    bower angular#>= 1.2.0 < 1.4.x            extract archive.tar.gz
    bower angular#>= 1.2.0 < 1.4.x           resolved git://github.com/angular/bower-angular.git#1.3.13
    bower google-diff-match-patch#*            export trunk
    bower google-diff-match-patch#*      invalid-meta google-diff-match-patch is missing "main" entry in bower.json
    bower google-diff-match-patch#*      invalid-meta google-diff-match-patch is missing "ignore" entry in bower.json
    bower google-diff-match-patch#*          resolved http://google-diff-match-patch.googlecode.com/svn#*
    bower angular-diff-match-patch#~0.1.6     install angular-diff-match-patch#0.1.6
    bower angular-mocks#>= 1.2.0 < 1.4.x      install angular-mocks#1.3.13
    bower angular#>= 1.2.0 < 1.4.x            install angular#1.3.13
    bower google-diff-match-patch#*           install google-diff-match-patch#*
    bower                                     no-json No bower.json file to save to, use bower init to create one
    
    angular-diff-match-patch#0.1.6 bower_components\angular-diff-match-patch
    ├── angular#1.3.13
    ├── angular-mocks#1.3.13
    └── google-diff-match-patch#*
    
    angular-mocks#1.3.13 bower_components\angular-mocks
    └── angular#1.3.13
    
    angular#1.3.13 bower_components\angular
    
    google-diff-match-patch#* bower_components\google-diff-match-patch
    PS C:\Users\aweiss\Documents\repos\testing>

Verify you have svn installed and try again.

**Comment by PurpleSun** [comment]
SVN was installed before I run that command.
Being in China, seems it was caused by The GFW.
Still figuring it out.

**Comment by amweiss** [comment]
I'll close this for now then, let me know if I can help.

**Comment by PurpleSun** [comment]
Set up a proxy for svn by edit `~/.subversion/servers` worked for me finally.
Thanks!
