### ISSUE TITLE
unable to install...

### ISSUE THREAD

**Issue by dotob** [amweiss/angular-diff-match-patch#8]
sorry perhaps this is noob, but can you tell me why this isnt working:

⇒  bower install angular-diff-match-patch
bower angular-diff-match-patch#*           cached git://github.com/amweiss/angular-diff-match-patch.git#0.1.6
bower angular-diff-match-patch#*         validate 0.1.6 against git://github.com/amweiss/angular-diff-match-patch.git#*
bower google-diff-match-patch#~0.1.0       cached git://github.com/friedolinfoerder/google-diff-match-patch.git#0.1.0
bower google-diff-match-patch#~0.1.0     validate 0.1.0 against git://github.com/friedolinfoerder/google-diff-match-patch.git#~0.1.0
bower google-diff-match-patch#*         ENOTFOUND Package svn+http://google-diff-match-patch.googlecode.com/svn/ not found

**Comment by amweiss** [comment]
I can't reproduce your issue, but it seems like SVN might be missing and
required?

C:\Users\aweiss\Documents\repos\tmp> bower install angular-diff-match-patch
bower angular-diff-match-patch#*           cached git://
github.com/amweiss/angular-diff-match-patch.git#0.1.6
bower angular-diff-match-patch#*         validate 0.1.6 against git://
github.com/amweiss/angular-diff-match-patch.git#*
bower google-diff-match-patch#*        not-cached svn+
http://google-diff-match-patch.googlecode.com/svn/#*
bower google-diff-match-patch#*           resolve svn+
http://google-diff-match-patch.googlecode.com/svn/#*
bower angular-mocks#>= 1.2.0 < 1.4.x       cached git://
github.com/angular/bower-angular-mocks.git#1.3.13
bower angular-mocks#>= 1.2.0 < 1.4.x     validate 1.3.13 against git://
github.com/angular/bower-angular-mocks.git#>= 1.2.0 < 1.4.x
bower angular#>= 1.2.0 < 1.4.x             cached git://
github.com/angular/bower-angular.git#1.3.13
bower angular#>= 1.2.0 < 1.4.x           validate 1.3.13 against git://
github.com/angular/bower-angular.git#>= 1.2.0 < 1.4.x
bower angular-mocks#>= 1.2.0 < 1.4.x          new version for git://
github.com/angular/bower-angular-mocks.git#>= 1.2.0 < 1.4.x
bower angular-mocks#>= 1.2.0 < 1.4.x      resolve git://
github.com/angular/bower-angular-mocks.git#>= 1.2.0 < 1.4.x
bower angular#>= 1.2.0 < 1.4.x                new version for git://
github.com/angular/bower-angular.git#>= 1.2.0 < 1.4.x
bower angular#>= 1.2.0 < 1.4.x            resolve git://
github.com/angular/bower-angular.git#>= 1.2.0 < 1.4.x
bower angular-mocks#>= 1.2.0 < 1.4.x     download
https://github.com/angular/bower-angular-mocks/archive/v1.3.14.tar.gz
bower angular#>= 1.2.0 < 1.4.x           download
https://github.com/angular/bower-angular/archive/v1.3.14.tar.gz
bower angular-mocks#>= 1.2.0 < 1.4.x      extract archive.tar.gz
bower angular#>= 1.2.0 < 1.4.x            extract archive.tar.gz
bower angular-mocks#>= 1.2.0 < 1.4.x     resolved git://
github.com/angular/bower-angular-mocks.git#1.3.14
bower angular#>= 1.2.0 < 1.4.x           resolved git://
github.com/angular/bower-angular.git#1.3.14
bower google-diff-match-patch#*            export trunk
bower google-diff-match-patch#*      invalid-meta google-diff-match-patch
is missing "main" entry in bower.json
bower google-diff-match-patch#*      invalid-meta google-diff-match-patch
is missing "ignore" entry in bower.json
bower google-diff-match-patch#*          resolved
http://google-diff-match-patch.googlecode.com/svn#*
bower angular-diff-match-patch#~0.1.6     install
angular-diff-match-patch#0.1.6
bower angular-mocks#>= 1.2.0 < 1.4.x      install angular-mocks#1.3.14
bower angular#>= 1.2.0 < 1.4.x            install angular#1.3.14
bower google-diff-match-patch#*           install google-diff-match-patch#*

angular-diff-match-patch#0.1.6 bower_components\angular-diff-match-patch
├── angular#1.3.14
├── angular-mocks#1.3.14
└── google-diff-match-patch#*

angular-mocks#1.3.14 bower_components\angular-mocks
└── angular#1.3.14

angular#1.3.14 bower_components\angular

google-diff-match-patch#* bower_components\google-diff-match-patch
PS C:\Users\aweiss\Documents\repos\tmp>

**Comment by dotob** [comment]
hi, dont know what it was. just tried it today and it worked. thanks for looking into it.
